# Generated by Django 2.1 on 2018-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nickgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nick',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
